#ifndef PLL_H
#define PLL_H



// OSCILLATOR CONFIGURATION 
#WORD CLKDIV = 0x0744         //PLLPOST(6,7) - PLLPRE(0,1,2,3,4) 

#BIT PLLPOST_0 = CLKDIV.6 
#BIT PLLPOST_1 = CLKDIV.7 

#BIT PLLPRE_0 = CLKDIV.0 
#BIT PLLPRE_1 = CLKDIV.1 
#BIT PLLPRE_2 = CLKDIV.2 
#BIT PLLPRE_3 = CLKDIV.3 
#BIT PLLPRE_4 = CLKDIV.4 

#WORD PLLFBD = 0x0746         //PLLDIV(0,1,2,3,4,5,6,7,8) 

#BIT PLLDIV_0 = PLLFBD.0 
#BIT PLLDIV_1 = PLLFBD.1 
#BIT PLLDIV_2 = PLLFBD.2 
#BIT PLLDIV_3 = PLLFBD.3 
#BIT PLLDIV_4 = PLLFBD.4 
#BIT PLLDIV_5 = PLLFBD.5 
#BIT PLLDIV_6 = PLLFBD.6 
#BIT PLLDIV_7 = PLLFBD.7 
#BIT PLLDIV_8 = PLLFBD.8


void init_PLL(); 

#endif
